name: continuous-integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6.15", "3.7.15", "3.8.15", "3.9.16", "3.10.9", "3.11.1"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt -r requirements.txt -c constraints.txt
    - name: Typecheck
      run: |
        make mypy
    - name: Lint
      run: |
        make -j4 lint
    - name: Test
      run: |
        pwd
        export PYTHONPATH=".":$PYTHONPATH
        make test
